<a href="https://colab.research.google.com/github/Kimbaeda/youngwoo/blob/main/5%EC%9D%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5_%EC%88%9C%ED%99%98_%EC%8B%A0%EA%B2%BD%EB%A7%9D(RNN%2C_LSTM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN

In [ ]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(2,10)))

model.summary()


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10)))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (8, 3)                    42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10), return_sequences=True))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


## 파이썬으로 RNN구현하기

$$ h_t = tanh(W_x X_t + W_h H_{t-1} + b)$$

```
의사코드
hidden_State_t = 0
for input_t in input_length: #각 시점마다 입력을 받는다.
    output_t = tanh(input_t, hidden_stat_t) #각 시점에 대해서 입력과 은닉 상태를 가지고 연산
    hidden_stat_t = output_t # 계산결과는 현재 시점의 은닉 상태가 된다.
```

In [ ]:
import numpy as np
timesteps = 10 # 시점의 수, NLP에서는 보통 문장의 길이
input_dim = 4 # 입력의 차원, NLP에서는 보통 단어 벡터의 차원
hidden_size = 8 # 은닉 상태의 크기 (메모리 셀의 용량)

inputs = np.random.random((timesteps, input_dim)) # 입력에 해당되는 2D 텐서

hidden_state_t = np.zeros((hidden_size, )) # 은닉 상태의 크기 hidden_size로 은닉 상태를 만듬.초기 은닉상태는 0(벡터)로 초기화


In [ ]:
# 초기 은닉 상태 출력
print(hidden_state_t)

# 8의 차원을 가지는 0의 값으로 구성된 벡터가 출력

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 가중치와 편향 정의

Wx = np.random.random((hidden_size, input_dim)) # (8, 4) 입력에 대한 가중치
Wh = np.random.random((hidden_size, hidden_size)) # (8, 8) 은닉상태에 대한 가중치
b = np.random.random((hidden_size, )) # (8, ) 편향

In [ ]:
# 가중치와 편향의 크기 출력

print(np.shape(Wx)) # (은닉상태의 크기 * 입력의 차원)
print(np.shape(Wh)) # (은닉상태의 크기 * 은닉상태의 크기)
print(np.shape(b)) # (은닉상태의 크기)

(8, 4)
(8, 8)
(8,)


In [ ]:
total_hidden_state = []

# 메모리 셀 동작
for input_t in inputs:
  output_t = np.tanh(np.dot(Wx, input_t)+ np.dot(Wh, hidden_state_t)+b) 
  total_hidden_state.append(list(output_t))
  print(np.shape(total_hidden_state)) #각 시점 t별 메모리 셀의 출력의 크기는 (timestep, output_dim)
  hidden_state_t = output_t

total_hidden_state = np.stack(total_hidden_state, axis=0)  # ( 1, 2, 3)


print(total_hidden_state) # (timesteps , outputdim) 크기

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)
[[0.87512627 0.94447423 0.93403891 0.74486162 0.90551458 0.91603446
  0.64511058 0.92670881]
 [0.99979057 0.99975184 0.99928276 0.99977938 0.99870682 0.9968624
  0.98742638 0.9963913 ]
 [0.99999349 0.99999611 0.9999022  0.99998545 0.99982929 0.999921
  0.99838883 0.99978475]
 [0.99999561 0.99999754 0.99995397 0.99999185 0.99985812 0.99994639
  0.99805072 0.99988388]
 [0.99998469 0.99999204 0.99987092 0.99998265 0.99974013 0.99986652
  0.99743091 0.99949556]
 [0.99999189 0.99998969 0.99990293 0.99998352 0.99977978 0.99977161
  0.99811149 0.99954465]
 [0.99999261 0.99999712 0.99994792 0.99999294 0.99983233 0.99994176
  0.99827417 0.99973568]
 [0.999996   0.99999804 0.9999006  0.99998791 0.99987803 0.99995589
  0.99915269 0.9998359 ]
 [0.9999888  0.9999948  0.99991911 0.99998729 0.99977649 0.99991086
  0.99689449 0.9997388 ]
 [0.99998465 0.99998916 0.99992037 0.99998637 0.99971379 0.9998094
  0.99620737 0.99950576]]


## 양방향 순환 신경망 (Bidirectional Recurrent Neural Network)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Bidirectional

model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences= True), input_shape=(timesteps, input_dim)))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional (Bidirectional (None, 10, 16)            208       
Total params: 208
Trainable params: 208
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences= True), input_shape=(timesteps, input_dim)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences= True)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences= True)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences= True)))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_1 (Bidirection (None, 10, 16)            208       
_________________________________________________________________
bidirectional_2 (Bidirection (None, 10, 16)            400       
_________________________________________________________________
bidirectional_3 (Bidirection (None, 10, 16)            400       
_________________________________________________________________
bidirectional_4 (Bidirection (None, 10, 16)            400       
Total params: 1,408
Trainable params: 1,408
Non-trainable params: 0
_________________________________________________________________


```

Quiz
1. Embedding을 사용하여 단어 집합(Vocabulary)의 크기가 5,000이고, 임베딩 벡터의 차원은 100입니다.
2. 은닉층에서 Simple RNN을 사용하여 은닉상태의 크기는 128이다.
3. 훈련에 사용하는 모든 샘플의 길이는 30으로 가정
4. 이진 분류를 수행하는 모델로, 출력층의 뉴련은 1개로 시그모이드 함수를 사용
5. 은닉층은 1개
총 파라미터 갯수를 구하시오.

```


In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Embedding, Dense

vocab_size = 5000
embedding_dim = 100
hidden_size =128

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_size))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 100)         500000    
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 128)               29312     
_________________________________________________________________
dense (Dense)                (None, 1)                 129       
Total params: 529,441
Trainable params: 529,441
Non-trainable params: 0
_________________________________________________________________


```
정답 풀이

Embedding = 5000(input) * 100(embedding) = 500,000
Wx = 100(embedding) * 128(hidden) = 12,800
Wh = 128 * 128 = 16,384
b(hidden) = 128
Wy = 128
b(output) = 1

total = 529,441
```

## 임의의 입력으로 SimpleRNN과 LSTM 이해하기

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [ ]:
# 임의의 데이터 생성 : 벡터의 차원은 5, 문장의 길이가 4인 경우를 가정

train_x = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_x)) # 단어 벡터의 차원은 5이고, 문장의 길이가 4인 경우를 가정한 입력

(4, 5)


In [ ]:
# RNN은 3D텐서를 입력 받으므로 배치 크기 1을 추가
'''
batch_size는 한 번에 RNN이 학습하는 데이터의 양을 의미하지만, 여기서는 샘플이 1개 밖에 없으므로 batch_size는 1
'''

train_x = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_x = np.array(train_x, dtype=np.float32)
print(train_x.shape) # (batch_size, timesteps, input_dim)

(1, 4, 5)


### SimpleRNN 이해하기

In [ ]:
rnn = SimpleRNN(3) # 은닉상태 크기3
# rnn = SimpleRNN(3, return_sequances=False, return_state=False) 와 동일

hidden_state = rnn(train_x)

print(f'hidden state : {hidden_state}, shape : {hidden_state.shape}')

hidden state : [[-0.10012155 -0.4721135   0.9712897 ]], shape : (1, 3)


In [ ]:
# return_sequances=True로 지정하여 모든 시점의 은닉 상태를 출력

rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_x)

print(f'hidden states : {hidden_states}, shape: {hidden_states.shape}')

hidden states : [[[ 0.84508294  0.787636    0.7427113 ]
  [ 0.45071793 -0.97736585  0.15795752]
  [-0.9419455  -0.8677167   0.973826  ]
  [ 0.93749696 -0.511277    0.76308835]]], shape: (1, 4, 3)


In [ ]:
# return_sequances=True 이면서, return_state=True로 할 경우

rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_x)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[-0.5369042   0.99727297  0.9999473 ]
  [-0.0126954   0.9167868   0.9965076 ]
  [ 0.8746314  -0.10798592  0.9873774 ]
  [ 0.96880627 -0.6339288   0.9354319 ]]], shape: (1, 4, 3)
last hidden state : [[ 0.96880627 -0.6339288   0.9354319 ]], shape: (1, 3)


In [ ]:
# return_sequances=False 이면서, return_state=True로 할 경우

rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_x)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden state : [[ 0.7497584 -0.9952875 -0.2872519]], shape: (1, 3)
last hidden state : [[ 0.7497584 -0.9952875 -0.2872519]], shape: (1, 3)


### LSTM 이해하기

- 실제로 SimpleRNN이 사용되는 경우는 거의 없습니다. 이보다는 LSTM이나 GRU을 주로 사용

In [ ]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_x)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[ 0.2080072  -0.12892686  0.18994214]], shape: (1, 3)
last hidden state : [[ 0.2080072  -0.12892686  0.18994214]], shape: (1, 3)
last cell state : [[ 0.34484416 -0.18498126  0.26371518]], shape: (1, 3)


SimpleRNN 때와는 달리, 세 개의 결과를 반환. return_sequences가 False이므로 우선 첫번째 결과는 마지막 시점의 은닉 상태임. 그런데 LSTM이 SimpleRNN과 다른 점은 return_state를 True로 둔 경우에는 마지막 시점의 은닉 상태뿐만 아니라 셀 상태까지 반환한다는 점이다.

In [ ]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_x)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden states : [[[-0.18496436  0.06714023 -0.6520807 ]
  [-0.15225704  0.12760682 -0.7629222 ]
  [-0.21280442  0.29162312 -0.78596616]
  [-0.13513148  0.25786963 -0.61566585]]], shape: (1, 4, 3)
last hidden state : [[-0.13513148  0.25786963 -0.61566585]], shape: (1, 3)
last cell state : [[-0.27661422  1.0972171  -2.1432161 ]], shape: (1, 3)


return_state가 True이므로 두번째 출력값이 마지막 은닉 상태, 세번째 출력값이 마지막 셀 상태인 것은 변함없지만 return_sequences가 True이므로 첫번째 출력값은 모든 시점의 은닉 상태가 출력

### Bidirectional(LSTM) 이해하기

In [ ]:
# 은닉상태 값 고정

k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [ ]:
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_x)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape: (1, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [ ]:
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_x)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


## RNN을 이용한 텍스트 생성(Text Generation)
- 다 대 일 (many to one)구조의 RNN을 사용하여 문맥을 반영해서 텍스트를 생성하는 모델을 만들어 보자
- '경마장에 있는 말이 뛰고 있다'
- '그의 말이 법이다'
- '가는 말이 고와야 오는 말이 곱다'

In [ ]:
import pandas as pd
# 위 3문장을 재구성하면, 아래와 같이 총 11개의 샘플이 구성됨
content = [['경마장에', '있는'],['경마장에 있는','말이'],['경마장에 있는 말이', '뛰고'],['경마장에 있는 말이 뛰고','있다'], \
           ['그의','말이'],['그의 말이','법이다'],['가는', '말이'],['가는 말이','고와야'],['가는 말이 고와야','오는'], \
           ['가는 말이 고와야 오는','말이'],['가는 말이 고와야 오는 말이','곱다']]
df = pd.DataFrame(content)
df.index = ['1', '2', '3', '4', '5', '6', '7', '8', '9','10','11']
df.columns = ['X', 'y']
df

X    y
1              경마장에   있는
2           경마장에 있는   말이
3        경마장에 있는 말이   뛰고
4     경마장에 있는 말이 뛰고   있다
5                그의   말이
6             그의 말이  법이다
7                가는   말이
8             가는 말이  고와야
9         가는 말이 고와야   오는
10     가는 말이 고와야 오는   말이
11  가는 말이 고와야 오는 말이   곱다

In [ ]:
list1 = [str(i) for i in range(1,12)]
print(list1)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']


### 데이터에 대한 이해와 전처리

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [ ]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [ ]:
# 단어집합을 생성, 크기를 확인
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) +1


# 케라스 토크나이저 정수 인코딩은 인덱스가 1부터 시작.
# 케라스 원-핫 인코딩에서 배열의 인덱스가 0부터 시작하기 때문에
# 배열의 크기를 실제 단어 집합의 크기보다 +1 로 생성해야함 그래서 미리 +1 선언
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [ ]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [ ]:
# 훈련데이터 만들기
sequences = list()
for line in text.split('\n'): # Wn을 기준으로 문장 토큰화
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 11


In [ ]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [ ]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print(f'샘플의 최대 길이 : {max_len}')

샘플의 최대 길이 : 6


In [ ]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [ ]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [ ]:
sequences = np.array(sequences)
x = sequences[:, :-1]
y = sequences[:, -1]
# 리스트의 마지막 값을 제외하고 저장한 것은 x
# 리스트의 마지막 값만 저장한 것은 y, -> 레이블에 해당

In [ ]:
print(x)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [ ]:
print(y) # 모든 샘플에 대한 레이블 출력

[ 3  1  4  5  1  7  1  9 10  1 11]


In [ ]:
y = to_categorical(y, num_classes=vocab_size)

In [ ]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### 모델 설계하기

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.4832 - accuracy: 0.0909
Epoch 2/200
1/1 - 0s - loss: 2.4692 - accuracy: 0.0909
Epoch 3/200
1/1 - 0s - loss: 2.4551 - accuracy: 0.0909
Epoch 4/200
1/1 - 0s - loss: 2.4409 - accuracy: 0.0909
Epoch 5/200
1/1 - 0s - loss: 2.4264 - accuracy: 0.0909
Epoch 6/200
1/1 - 0s - loss: 2.4115 - accuracy: 0.0909
Epoch 7/200
1/1 - 0s - loss: 2.3962 - accuracy: 0.1818
Epoch 8/200
1/1 - 0s - loss: 2.3803 - accuracy: 0.1818
Epoch 9/200
1/1 - 0s - loss: 2.3638 - accuracy: 0.1818
Epoch 10/200
1/1 - 0s - loss: 2.3467 - accuracy: 0.2727
Epoch 11/200
1/1 - 0s - loss: 2.3288 - accuracy: 0.4545
Epoch 12/200
1/1 - 0s - loss: 2.3102 - accuracy: 0.3636
Epoch 13/200
1/1 - 0s - loss: 2.2907 - accuracy: 0.3636
Epoch 14/200
1/1 - 0s - loss: 2.2705 - accuracy: 0.3636
Epoch 15/200
1/1 - 0s - loss: 2.2496 - accuracy: 0.3636
Epoch 16/200
1/1 - 0s - loss: 2.2278 - accuracy: 0.3636
Epoch 17/200
1/1 - 0s - loss: 2.2054 - accuracy: 0.3636
Epoch 18/200
1/1 - 0s - loss: 2.1824 - accuracy: 0.3636
E

In [ ]:
# # 문장을 생성하는 함수 만들어서 출력하기
# def sentence_generation(model, t, current_word, n):
#   init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기 위해 저장
#   sentence = ''
#   for _ in range(n): # n번 반복
#     encoded = t.texts_to_sequences([current_word][0]) # 현재 단어에 대한 정수 인코딩
#     encoded = pad_sequences([encoded], maxlen=5, padding='pre') # 데이터에 대한 패딩
#     result = model.predict_classes(encoded, verbose=0) # 입력한 X(현재 단어)
#     for word, index in t.word_index.items():
#       if index == result: # 만약 예측한 단어와 인덱스가 동일한 단어가 있다면
#         break # 해당 단어가 예측 단어이므로 break
#     current_word = current_word + ' ' + word # 현재 단어 + ' ' + 옟ㄱ 단어를 현재단어로 변경
#     sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
  
#   sentence = init_word + sentence_generation
#   return sentence

def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=5, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [ ]:
print(sentence_generation(model, t, '경마장에', 4))
# '경마장에' 라는 단어 뒤에는 총 4개의 단어가 있으므로 4번 예측

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


경마장에 있는 말이 뛰고 있다


In [ ]:
print(sentence_generation(model, t, '그의', 2)) # 2번 예측

그의 말이 법이다


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
print(sentence_generation(model, t, '가는', 5)) # 5번 예측

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


가는 말이 고와야 오는 말이 곱다


In [ ]:
print(sentence_generation(model, t, '말이', 7))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


말이 말이 고와야 오는 말이 곱다 곱다 오는


## LSTM을 이용한 텍스트 생성

In [ ]:
# /content/drive/MyDrive/Colab Notebooks/자연어처리/ArticlesApril2018.csv

In [ ]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/자연어처리/ArticlesApril2018.csv')
df.head()

articleID  ...                                             webURL
0  5adf6684068401528a2aa69b  ...  https://www.nytimes.com/2018/04/24/sports/foot...
1  5adf653f068401528a2aa697  ...  https://www.nytimes.com/2018/04/24/climate/epa...
2  5adf4626068401528a2aa628  ...  https://www.nytimes.com/2018/04/24/dining/noma...
3  5adf40d2068401528a2aa619  ...  https://www.nytimes.com/2018/04/24/world/europ...
4  5adf3d64068401528a2aa60f  ...  https://www.nytimes.com/2018/04/24/world/canad...

[5 rows x 15 columns]

In [ ]:
# Null이 있는지 확인
df.isna().sum()

articleID           0
articleWordCount    0
byline              0
documentType        0
headline            0
keywords            0
multimedia          0
newDesk             0
printPage           0
pubDate             0
sectionName         0
snippet             0
source              0
typeOfMaterial      0
webURL              0
dtype: int64

In [ ]:
# headlin열에서 모든 신문 기사의 제목을 뽑아서 하나의 리스트로 저장
# df.columns
# 내가 한거
headline = df['headline'].values.tolist()
## 강사님
# headline = []
# headline.extend(list(df.headline.values)) #헤드라인의 값들을 리스트로 저장

In [ ]:
# 상위 5개만 출력
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [ ]:
# 총 샘플의 갯수
len(headline)

1324

In [ ]:
# unknown값을 가진 샘플 제거
# 제거 후 샘플의 갯수 출력
headline = [n for n in headline if n != "Unknown"]
print('노이즈 값 제거 후 샘플의 갯수 : {}'.format(len(headline)))

노이즈 값 제거 후 샘플의 갯수 : 1214


In [ ]:
# 상위 5개만 출력
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [ ]:
# 전처리 수행

def repreprocessing(s):
    s=s.encode("utf8").decode("ascii",'ignore')
    return ''.join(c for c in s if c not in punctuation).lower() # 구두점 제거와 동시에 소문자화

text = [repreprocessing(x) for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [ ]:
# 단어 집합을 만들고 크기 확인

t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 3494


In [ ]:
# 정수 인코딩과 동시에 하나의 문장을 여러 줄로 분해하여 훈련 데이터를 구성
sequences = list()

for line in text: # 1,214 개의 샘플에 대해서 샘플을 1개씩 가져온다.
    encoded = t.texts_to_sequences([line])[0] # 각 샘플에 대한 정수 인코딩
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

sequences[:11] # 11개의 샘플 출력

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [ ]:
# 어떤 정수가 어떤 단어를 의미하는지 알아보기 위해 인덱스로부터 단어를 찾는 index_to_word를 생성

index_to_word={}
for key, value in t.word_index.items(): # 인덱스를 단어로 바꾸기 위해 index_to_word를 생성
    index_to_word[value] = key

print('빈도수 상위 582번 단어 : {}'.format(index_to_word[582]))

빈도수 상위 582번 단어 : offer


In [ ]:
for i in range(1,11):
  print(f'빈도수 상위 {i}번 단어 : {index_to_word[i]}')

빈도수 상위 1번 단어 : the
빈도수 상위 2번 단어 : a
빈도수 상위 3번 단어 : to
빈도수 상위 4번 단어 : of
빈도수 상위 5번 단어 : in
빈도수 상위 6번 단어 : for
빈도수 상위 7번 단어 : and
빈도수 상위 8번 단어 : is
빈도수 상위 9번 단어 : on
빈도수 상위 10번 단어 : with


In [ ]:
# 패딩

max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

샘플의 최대 길이 : 24
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [ ]:
# 맨 우측 단어만 레이블로 분리

sequences = np.array(sequences)
x = sequences[:,:-1]
y = sequences[:,-1]

print(x[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]


In [ ]:
print(y[:3]) # 레이블

[ 269  371 1115]


In [ ]:
y = to_categorical(y, num_classes=vocab_size) # 원핫 인코딩

In [ ]:
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### 모델 설계

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
# y데이터를 분리하였으므로 이제 X데이터의 길이는 기존 데이터의 길이 - 1
model.add(LSTM(128)) # 은닉상태 128
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=200, verbose=2)

Epoch 1/200
244/244 - 10s - loss: 7.6379 - accuracy: 0.0297
Epoch 2/200
244/244 - 8s - loss: 7.1110 - accuracy: 0.0296
Epoch 3/200
244/244 - 8s - loss: 6.9758 - accuracy: 0.0350
Epoch 4/200
244/244 - 8s - loss: 6.8547 - accuracy: 0.0397
Epoch 5/200
244/244 - 8s - loss: 6.7070 - accuracy: 0.0452
Epoch 6/200
244/244 - 8s - loss: 6.5295 - accuracy: 0.0482
Epoch 7/200
244/244 - 8s - loss: 6.3421 - accuracy: 0.0491
Epoch 8/200
244/244 - 8s - loss: 6.1445 - accuracy: 0.0579
Epoch 9/200
244/244 - 8s - loss: 5.9480 - accuracy: 0.0615
Epoch 10/200
244/244 - 8s - loss: 5.7605 - accuracy: 0.0643
Epoch 11/200
244/244 - 8s - loss: 5.5819 - accuracy: 0.0700
Epoch 12/200
244/244 - 8s - loss: 5.4171 - accuracy: 0.0743
Epoch 13/200
244/244 - 8s - loss: 5.2587 - accuracy: 0.0834
Epoch 14/200
244/244 - 8s - loss: 5.1103 - accuracy: 0.0814
Epoch 15/200
244/244 - 8s - loss: 4.9700 - accuracy: 0.0983
Epoch 16/200
244/244 - 8s - loss: 4.8338 - accuracy: 0.1061
Epoch 17/200
244/244 - 8s - loss: 4.7075 - accur

In [ ]:
# 문장 생성
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=23, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [ ]:
print(sentence_generation(model, t, 'i', 10))
# 임의의 단어 'i'에 대해서 10개의 단어를 추가 생성

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


i want to be rich and im not sorry attack about


In [ ]:
print(sentence_generation(model, t, 'how', 10))
# 임의의 단어 'how'에 대해서 10개의 단어를 추가 생성

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


how to win an argument about guns about greenpeace big old


In [ ]:
# epa to unveil a new rule its effect less science in policymakin
print(sentence_generation(model, t, 'epa', 11))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


epa to unveil a new rule its effect less science in policymaking


In [ ]:
'''
'former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression'
'''
print(sen)