# 노션 정리 링크
https://www.notion.so/12-Pandas-3ee9267e0bc2427b8741781cafe8acdc

# Pandas의 1차원 자료형 - Series

In [1]:
import pandas as pd

In [2]:
a = {'a': 10, 'b':20, 'c':30, 'd':40, 'e':50}

In [3]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [4]:
type(a)

dict

In [5]:
b = pd.Series(a)

In [6]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [7]:
type(b)

pandas.core.series.Series

In [8]:
b.shape

(5,)

In [9]:
import numpy as np

In [10]:
aa = np.arange(3, 10)

In [11]:
aa

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
aa.shape

(7,)

In [12]:
bb = pd.Series(aa)

In [13]:
bb

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int32

In [15]:
bb.shape

(7,)

In [16]:
type(bb)

pandas.core.series.Series

In [17]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [18]:
a.values()

dict_values([10, 20, 30, 40, 50])

In [19]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [23]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [24]:
c =[10,20,30,40,50]

In [25]:
d = pd.Series(c)

In [26]:
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [27]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [28]:
d.values

array([10, 20, 30, 40, 50], dtype=int64)

In [29]:
e = ['a','b','c','d','e']
f = [10, 20, 30, 40, 50]

In [30]:
g = pd.Series(f, index = e)

In [31]:
g

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [32]:
g.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [33]:
g.values

array([10, 20, 30, 40, 50], dtype=int64)

In [34]:
g['a']

10

In [35]:
g[0]

10

In [36]:
g['a':'d']

a    10
b    20
c    30
d    40
dtype: int64

In [38]:
g[0:3]

a    10
b    20
c    30
dtype: int64

# Pandas의 2차원 자료형 - DataFrame

In [10]:
import pandas as pd
import numpy as np

In [2]:
a = {'a':[1,2,3],'b':[1,3,5],'c':[2,4,6],'d':[3,6,9]}

In [3]:
a

{'a': [1, 2, 3], 'b': [1, 3, 5], 'c': [2, 4, 6], 'd': [3, 6, 9]}

In [4]:
df1 = pd.DataFrame(a)

In [5]:
df1

a  b  c  d
0  1  1  2  3
1  2  3  4  6
2  3  5  6  9

In [7]:
type(df1)

pandas.core.frame.DataFrame

In [8]:
df1.shape

(3, 4)

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       3 non-null      int64
dtypes: int64(4)
memory usage: 224.0 bytes


In [12]:
b = np.arange(12).reshape(3,4)

In [13]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
df2 = pd.DataFrame(b)

In [15]:
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [16]:
type(df2)

pandas.core.frame.DataFrame

In [17]:
df2.shape

(3, 4)

In [19]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int32
 1   1       3 non-null      int32
 2   2       3 non-null      int32
 3   3       3 non-null      int32
dtypes: int32(4)
memory usage: 176.0 bytes


In [20]:
df = pd.DataFrame([[1,20,'서울'],[2,25,'대전']],
                 index = ['홍길동','홍길순'],
                 columns = ['순서','나이','지역'])

In [21]:
df

순서  나이  지역
홍길동   1  20  서울
홍길순   2  25  대전

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
df.shape

(2, 3)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 홍길동 to 홍길순
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   순서      2 non-null      int64 
 1   나이      2 non-null      int64 
 2   지역      2 non-null      object
dtypes: int64(2), object(1)
memory usage: 64.0+ bytes


In [26]:
df.index

Index(['홍길동', '홍길순'], dtype='object')

In [27]:
df.columns

Index(['순서', '나이', '지역'], dtype='object')

In [28]:
df.values

array([[1, 20, '서울'],
       [2, 25, '대전']], dtype=object)

In [29]:
df.index = ['사람1','사람2']

In [30]:
df

순서  나이  지역
사람1   1  20  서울
사람2   2  25  대전

In [31]:
df.columns = ['연번','연령','도시']

In [32]:
df

연번  연령  도시
사람1   1  20  서울
사람2   2  25  대전

In [33]:
df = df.rename(index = {'사람1':'홍길동'})

In [34]:
df

연번  연령  도시
홍길동   1  20  서울
사람2   2  25  대전

In [35]:
df = df.rename(columns = {'연번':'순서'})

In [36]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전

# Pandas의 2차원 자료형 - DataFrame
- 행 추가
- 열 추가
- 값 변경
- 행 삭제
- 열 삭제

In [37]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전

In [38]:
df.loc['사람3'] = [3, 30, '부산']

In [39]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산

In [40]:
df.loc['사람4'] = 0

In [41]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람4   0   0   0

In [42]:
df.loc['사람1'] = df.loc['홍길동']

In [43]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람4   0   0   0
사람1   1  20  서울

In [46]:
df['나이대'] = ['20대','20대','30대','0대','20대']

In [47]:
df

순서  연령  도시  나이대
홍길동   1  20  서울  20대
사람2   2  25  대전  20대
사람3   3  30  부산  30대
사람4   0   0   0   0대
사람1   1  20  서울  20대

In [48]:
df['직업'] = '학생'

In [49]:
df

순서  연령  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   0   0   0   0대  학생
사람1   1  20  서울  20대  학생

In [50]:
df.loc['사람4','순서'] = 4

In [51]:
df

순서  연령  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   4   0   0   0대  학생
사람1   1  20  서울  20대  학생

In [52]:
df.iloc[3,1] = 10

In [53]:
df

순서  연령  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   4  10   0   0대  학생
사람1   1  20  서울  20대  학생

In [54]:
df.loc['사람4',['도시','나이대']] = '광주','10대'

In [55]:
df

순서  연령  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   4  10  광주  10대  학생
사람1   1  20  서울  20대  학생

In [56]:
df.iloc[3,[1,3]] = 40,'40대'

In [57]:
df

순서  연령  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람4   4  40  광주  40대  학생
사람1   1  20  서울  20대  학생

In [58]:
df = df.drop('사람4', axis = 0)

In [59]:
df

순서  연령  도시  나이대  직업
홍길동   1  20  서울  20대  학생
사람2   2  25  대전  20대  학생
사람3   3  30  부산  30대  학생
사람1   1  20  서울  20대  학생

In [60]:
df = df.drop(['나이대','직업'], axis =1)

In [61]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   1  20  서울

In [66]:
a = list(range(1,101))

# Pandas의 2차원 자료형 - DataFrame
- 전체 복사
- 부분 복사

In [68]:
df2 = df

In [69]:
df2

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   1  20  서울

In [70]:
df2.loc['사람1','순서'] = 4

In [71]:
df2

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [72]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [73]:
df3 = df.copy()

In [74]:
df3

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [75]:
df3.loc['사람1','순서'] = 5

In [76]:
df3

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   5  20  서울

In [77]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [78]:
hong = df.loc['홍길동']

In [79]:
hong

순서     1
연령    20
도시    서울
Name: 홍길동, dtype: object

In [80]:
type(hong)

pandas.core.series.Series

In [81]:
hong.shape

(3,)

In [82]:
gil = df.iloc[0]

In [83]:
gil

순서     1
연령    20
도시    서울
Name: 홍길동, dtype: object

In [84]:
type(gil)

pandas.core.series.Series

In [85]:
gil.shape

(3,)

In [87]:
df4 = df.loc[['홍길동','사람1']]

In [88]:
df4

순서  연령  도시
홍길동   1  20  서울
사람1   4  20  서울

In [89]:
df5 = df.iloc[[0,3]]

In [90]:
df5

순서  연령  도시
홍길동   1  20  서울
사람1   4  20  서울

In [91]:
df6 = df.loc['홍길동':'사람3']

In [92]:
df6

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산

In [93]:
df7 = df.iloc[0:3]

In [94]:
df7

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산

In [97]:
df

순서  연령  도시
홍길동   1  20  서울
사람2   2  25  대전
사람3   3  30  부산
사람1   4  20  서울

In [99]:
df8 = df[['연령']]

In [100]:
df8

연령
홍길동  20
사람2  25
사람3  30
사람1  20

In [102]:
df9 = df['연령']

In [103]:
df9

홍길동    20
사람2    25
사람3    30
사람1    20
Name: 연령, dtype: int64

In [104]:
type(df8)

pandas.core.frame.DataFrame

In [105]:
type(df9)

pandas.core.series.Series

In [106]:
df10 = df[['연령','도시']]

In [107]:
df10

연령  도시
홍길동  20  서울
사람2  25  대전
사람3  30  부산
사람1  20  서울

In [117]:
df10

연령  도시
홍길동  20  서울
사람2  25  대전
사람3  30  부산
사람1  20  서울

In [119]:
df11 = df.loc[['홍길동','사람1'],['연령','도시']]

In [120]:
df11

연령  도시
홍길동  20  서울
사람1  20  서울

In [121]:
df12 = df.iloc[[0,3],[1,2]]

In [122]:
df12

연령  도시
홍길동  20  서울
사람1  20  서울

# Pandas의 2차원 자료형 - DataFrame
- 인덱스
- 정렬
- 전치
- 치환

In [123]:
a = {'이름':['홍길동','사람1','사람2'],'나이':[20,30,25],'도시':['서울','서울','대전']}

In [124]:
a

{'이름': ['홍길동', '사람1', '사람2'], '나이': [20, 30, 25], '도시': ['서울', '서울', '대전']}

In [125]:
df = pd.DataFrame(a)

In [126]:
df

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울
2  사람2  25  대전

In [127]:
df2 = df.set_index('이름')

In [128]:
df2

나이  도시
이름         
홍길동  20  서울
사람1  30  서울
사람2  25  대전

In [129]:
df3 = df2.set_index('도시')

In [130]:
df3

나이
도시    
서울  20
서울  30
대전  25

In [131]:
df2

나이  도시
이름         
홍길동  20  서울
사람1  30  서울
사람2  25  대전

In [136]:
df2 = df2.reset_index()

In [144]:
df2

이름  나이  도시
2  사람2  25  대전
1  사람1  30  서울
0  홍길동  20  서울

In [138]:
df3 = df2.set_index('도시')

In [139]:
df3

이름  나이
도시         
서울  홍길동  20
서울  사람1  30
대전  사람2  25

In [163]:
df2 = df2.sort_index(ascending = False)

In [164]:
df2

이름  나이  도시  나이대
2  사람2  25  대전    2
1  사람1  30  서울    3
0  홍길동  20  서울    2

In [151]:
df2 = df2.sort_values(by = '나이', ascending = False)

In [152]:
df2

이름  나이  도시
1  사람1  30  서울
2  사람2  25  대전
0  홍길동  20  서울

In [153]:
df2 = df2.T

In [154]:
df2

1    2    0
이름  사람1  사람2  홍길동
나이   30   25   20
도시   서울   대전   서울

In [155]:
df2 = df2.T

In [156]:
df2

이름  나이  도시
1  사람1  30  서울
2  사람2  25  대전
0  홍길동  20  서울

In [157]:
df2['나이대'] = ['30대','20대','20대']

In [158]:
df2

이름  나이  도시  나이대
1  사람1  30  서울  30대
2  사람2  25  대전  20대
0  홍길동  20  서울  20대

In [159]:
b = {'20대':2,'30대':3}

In [160]:
df2['나이대'] = df2['나이대'].map(b)

In [161]:
df2

이름  나이  도시  나이대
1  사람1  30  서울    3
2  사람2  25  대전    2
0  홍길동  20  서울    2

In [162]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 1 to 0
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      3 non-null      object
 1   나이      3 non-null      object
 2   도시      3 non-null      object
 3   나이대     3 non-null      int64 
dtypes: int64(1), object(3)
memory usage: 200.0+ bytes


# Pandas의 기본 연산 - Series

In [165]:
a ={'a':10,'b':20,'c':30,'d':40,'e':50}

In [166]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [167]:
b = pd.Series(a)

In [168]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [169]:
type(b)

pandas.core.series.Series

In [170]:
b.shape

(5,)

In [171]:
c = b / 10

In [172]:
c

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [173]:
c = b // 10

In [174]:
c

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [176]:
d = b + c

In [177]:
d

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [178]:
e = {'a':10,'c':20,'e':30,'g':40}

In [179]:
f = pd.Series(e)

In [180]:
f

a    10
c    20
e    30
g    40
dtype: int64

In [181]:
d + f

a    21.0
b     NaN
c    53.0
d     NaN
e    85.0
g     NaN
dtype: float64

In [182]:
d.add(f, fill_value = 0)

a    21.0
b    22.0
c    53.0
d    44.0
e    85.0
g    40.0
dtype: float64

In [183]:
d.sub(f, fill_value = 0)

a     1.0
b    22.0
c    13.0
d    44.0
e    25.0
g   -40.0
dtype: float64

In [185]:
d.mul(f, fill_value = 1)

a     110.0
b      22.0
c     660.0
d      44.0
e    1650.0
g      40.0
dtype: float64

In [186]:
d.div(f, fill_value = 1)

a     1.100000
b    22.000000
c     1.650000
d    44.000000
e     1.833333
g     0.025000
dtype: float64

# Pandas의 기본 연산 - DataFrame

In [187]:
a = {'점수1':[10,20,30],'점수2':[40,50,60]}

In [188]:
df1 = pd.DataFrame(a)

In [189]:
df1

점수1  점수2
0   10   40
1   20   50
2   30   60

In [190]:
b = {'점수1':[100,200,300],'점수3':[400,500,600]}

In [191]:
df2 = pd.DataFrame(b)

In [192]:
df2

점수1  점수3
0  100  400
1  200  500
2  300  600

In [193]:
df3 = df1 + df2

In [194]:
df3

점수1  점수2  점수3
0  110  NaN  NaN
1  220  NaN  NaN
2  330  NaN  NaN

In [195]:
df4 = df1.add(df2, fill_value = 0)

In [196]:
df4

점수1   점수2    점수3
0  110  40.0  400.0
1  220  50.0  500.0
2  330  60.0  600.0

In [197]:
df5 = df1.sub(df2, fill_value = 0)

In [198]:
df5

점수1   점수2    점수3
0  -90  40.0 -400.0
1 -180  50.0 -500.0
2 -270  60.0 -600.0

In [199]:
df6 = df1.mul(df2, fill_value = 1)

In [200]:
df6

점수1   점수2    점수3
0  1000  40.0  400.0
1  4000  50.0  500.0
2  9000  60.0  600.0

In [201]:
df7 = df1.div(df2, fill_value = 1)

In [202]:
df7

점수1   점수2       점수3
0  0.1  40.0  0.002500
1  0.1  50.0  0.002000
2  0.1  60.0  0.001667

In [203]:
a = {'이름':['홍길동','사람1','사람2'], '나이':[20, 30, 25]}

In [204]:
df1 = pd.DataFrame(a)

In [206]:
df1

이름  나이
0  홍길동  20
1  사람1  30
2  사람2  25

In [207]:
b = {'이름':['홍길동','사람1','사람2'], '도시':['서울', '서울', '대전']}

In [208]:
df2 = pd.DataFrame(b)

In [209]:
df2

이름  도시
0  홍길동  서울
1  사람1  서울
2  사람2  대전

In [210]:
df = pd.merge(left = df1,
             right = df2,
             how = 'left',
             left_on = '이름',
             right_on = '이름')

In [211]:
df

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울
2  사람2  25  대전

In [212]:
x1 = (df['도시'] == '서울')

In [214]:
df[x1]

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울

In [215]:
x2 = (df['도시'] != '서울')

In [216]:
df[x2]

이름  나이  도시
2  사람2  25  대전

In [217]:
x3 = (df['나이'] < 30)

In [218]:
df[x3]

이름  나이  도시
0  홍길동  20  서울
2  사람2  25  대전

In [219]:
x4 = (df['도시'] == '서울') & (df['나이'] < 30)

In [220]:
df[x4]

이름  나이  도시
0  홍길동  20  서울

In [221]:
x5 = (df['도시'] == '서울') | (df['나이'] < 30)

In [222]:
df[x5]

이름  나이  도시
0  홍길동  20  서울
1  사람1  30  서울
2  사람2  25  대전